# Snippet
sulu_snippet.get_snippets:
    path: '/snippets.{_format}'
    methods: GET
    controller: 'sulu_snippet.controller.snippet::cgetAction'
    format: json
    requirements:
        _format: json|csv

sulu_snippet.get_snippet:
    path: '/snippets/{id}.{_format}'
    methods: GET
    controller: 'sulu_snippet.controller.snippet::getAction'
    format: json
    requirements:
        _format: json|csv

sulu_snippet.post_snippet:
    path: '/snippets.{_format}'
    methods: POST
    controller: 'sulu_snippet.controller.snippet::postAction'
    format: json
    requirements:
        _format: json|csv

sulu_snippet.put_snippet:
    path: '/snippets/{id}.{_format}'
    methods: PUT
    controller: 'sulu_snippet.controller.snippet::putAction'
    format: json
    requirements:
        _format: json|csv

sulu_snippet.delete_snippet:
    path: '/snippets/{id}.{_format}'
    methods: DELETE
    controller: 'sulu_snippet.controller.snippet::deleteAction'
    format: json
    requirements:
        _format: json|csv

sulu_snippet.post_snippet_trigger:
    path: '/snippets/{id}.{_format}'
    methods: POST
    controller: 'sulu_snippet.controller.snippet::postTriggerAction'
    format: json
    requirements:
        _format: json|csv

# Snippet Areas
sulu_snippet.get_snippet-areas:
    path: '/snippet-areas.{_format}'
    methods: GET
    controller: 'sulu_snippet.snippet_area_controller::cgetAction'
    format: json
    requirements:
        _format: json|csv

sulu_snippet.put_snippet-area:
    path: '/snippet-areas/{key}.{_format}'
    methods: PUT
    controller: 'sulu_snippet.snippet_area_controller::putAction'
    format: json
    requirements:
        _format: json|csv

sulu_snippet.delete_snippet-area:
    path: '/snippet-areas/{key}.{_format}'
    methods: DELETE
    controller: 'sulu_snippet.snippet_area_controller::deleteAction'
    format: json
    requirements:
        _format: json|csv

sulu_snippet.get_languages:
    path: '/languages.{_format}'
    methods: GET
    controller: 'sulu_snippet.language_controller::cgetAction'
    format: json
    requirements:
        _format: json|csv
