framework:
    secret: secret
    router: { resource: '%kernel.project_dir%/config/routing.yml' }
    test: ~
    profiler:
        enabled: false
    mailer:
        dsn: 'null://null'
        message_bus: false # else messenger component duplicates the message: https://github.com/symfony/symfony/issues/48004#issuecomment-2476617713

    lock: 'flock://%kernel.project_dir%/var/lock'

doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
    dbal:
        url: '%env(DATABASE_URL)%'

jms_serializer:
    metadata:
        debug: '%kernel.debug%'

flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/uploads'

cmsig_seal:
    # "TEST_TOKEN" is typically set by ParaTest
    index_name_prefix: 'test_%env(default::TEST_TOKEN)%'
    engines:
        default:
            adapter: 'memory://'
