sulu_routes.post_route:
    path: '/routes.{_format}'
    methods: POST
    controller: 'sulu_route.route_controller::postAction'
    format: json
    requirements:
        _format: json|csv

sulu_routes.get_routes:
    path: '/routes.{_format}'
    methods: GET
    controller: 'sulu_route.route_controller::cgetAction'
    format: json
    requirements:
        _format: json|csv

sulu_routes.delete_routes:
    path: '/routes.{_format}'
    methods: DELETE
    controller: 'sulu_route.route_controller::cdeleteAction'
    format: json
    requirements:
        _format: json|csv
