# Roles
sulu_security.get_roles:
    path: '/roles.{_format}'
    methods: GET
    controller: 'sulu_security.role_controller::cgetAction'
    format: json
    requirements:
        _format: json|csv

sulu_security.get_role:
    path: '/roles/{id}.{_format}'
    methods: GET
    controller: 'sulu_security.role_controller::getAction'
    format: json
    requirements:
        _format: json|csv

sulu_security.post_role:
    path: '/roles.{_format}'
    methods: POST
    controller: 'sulu_security.role_controller::postAction'
    format: json
    requirements:
        _format: json|csv

sulu_security.put_role:
    path: '/roles/{id}.{_format}'
    methods: PUT
    controller: 'sulu_security.role_controller::putAction'
    format: json
    requirements:
        _format: json|csv

sulu_security.delete_role:
    path: '/roles/{id}.{_format}'
    methods: DELETE
    controller: 'sulu_security.role_controller::deleteAction'
    format: json
    requirements:
        _format: json|csv

# Role Settings
sulu_security.get_role_setting:
    path: '/roles/{roleId}/settings/{key}.{_format}'
    methods: GET
    controller: 'sulu_security.role_setting_controller::getAction'
    format: json
    requirements:
        _format: json|csv

sulu_security.put_role_setting:
    path: '/roles/{roleId}/settings/{key}.{_format}'
    methods: PUT
    controller: 'sulu_security.role_setting_controller::putAction'
    format: json
    requirements:
        _format: json|csv

# Users
sulu_security.get_user:
    path: '/users/{id}.{_format}'
    methods: GET
    controller: 'sulu_security.user_controller::getAction'
    format: json
    requirements:
        _format: json|csv

sulu_security.post_user:
    path: '/users.{_format}'
    methods: POST
    controller: 'sulu_security.user_controller::postAction'
    format: json
    requirements:
        _format: json|csv

sulu_security.put_user:
    path: '/users/{id}.{_format}'
    methods: PUT
    controller: 'sulu_security.user_controller::putAction'
    format: json
    requirements:
        _format: json|csv

sulu_security.patch_user:
    path: '/users/{id}.{_format}'
    methods: PATCH
    controller: 'sulu_security.user_controller::patchAction'
    format: json
    requirements:
        _format: json|csv

sulu_security.delete_user:
    path: '/users/{id}.{_format}'
    methods: DELETE
    controller: 'sulu_security.user_controller::deleteAction'
    format: json
    requirements:
        _format: json|csv

sulu_security.get_users:
    path: '/users.{_format}'
    methods: GET
    controller: 'sulu_security.user_controller::cgetAction'
    format: json
    requirements:
        _format: json|csv

sulu_security.post_user_trigger:
    path: '/users/{id}.{_format}'
    methods: POST
    controller: 'sulu_security.user_controller::postTriggerAction'
    format: json
    requirements:
        _format: json|csv

# Permissions
sulu_security.get_permissions:
    path: '/permissions.{_format}'
    methods: GET
    controller: 'sulu_security.permission_controller::cgetAction'
    format: json
    requirements:
        _format: json|csv

sulu_security.put_permissions:
    path: '/permissions.{_format}'
    methods: PUT
    controller: 'sulu_security.permission_controller::cputAction'
    format: json
    requirements:
        _format: json|csv

# Profile
sulu_security.get_profile:
    path: '/profile.{_format}'
    methods: GET
    controller: 'sulu_security.profile_controller::getAction'
    format: json
    requirements:
        _format: json|csv

sulu_security.put_profile:
    path: '/profile.{_format}'
    methods: PUT
    controller: 'sulu_security.profile_controller::putAction'
    format: json
    requirements:
        _format: json|csv

sulu_security.patch_profile_settings:
    path: '/profile/settings.{_format}'
    methods: PATCH
    controller: 'sulu_security.profile_controller::patchSettingsAction'
    format: json
    requirements:
        _format: json|csv

sulu_security.delete_profile_settings:
    path: '/profile/settings.{_format}'
    methods: DELETE
    controller: 'sulu_security.profile_controller::deleteSettingsAction'
    format: json
    requirements:
        _format: json|csv
