sulu_page.get_pages:
    path: /pages.{_format}
    methods: GET
    controller: sulu_page.admin_page_controller::cgetAction
    format: json

sulu_page.get_page:
    path: /pages/{id}.{_format}
    methods: GET
    controller: sulu_page.admin_page_controller::getAction
    format: json

sulu_page.post_page:
    path: /pages.{_format}
    methods: POST
    controller: sulu_page.admin_page_controller::postAction
    format: json

sulu_page.put_page:
    path: /pages/{id}.{_format}
    methods: PUT
    controller: sulu_page.admin_page_controller::putAction
    format: json

sulu_page.delete_page:
    path: /pages/{id}.{_format}
    methods: DELETE
    controller: sulu_page.admin_page_controller::deleteAction
    format: json

sulu_page.post_page_trigger:
    path: /pages/{id}.{_format}
    methods: POST
    controller: sulu_page.admin_page_controller::postTriggerAction
    format: json

sulu_page.get_page_versions:
    path: /pages/{id}/versions.{_format}
    methods: GET
    controller: sulu_page.admin_page_controller::getVersionsAction
    format: json
