sulu_admin.collaboration_controller:
    type: rest
    name_prefix: sulu_admin.
    resource: sulu_admin.collaboration_controller

sulu_admin.icon:
    type: rest
    name_prefix: sulu_admin.
    resource: sulu_admin.icon_controller
