# Collaboration
sulu_admin.put_collaborations:
    path: /collaborations.{_format}
    controller: sulu_admin.collaboration_controller::cputAction
    methods: PUT
    format: json
    requirements:
        _format: json|csv

sulu_admin.delete_collaborations:
    path: /collaborations.{_format}
    controller: sulu_admin.collaboration_controller::cdeleteAction
    methods: DELETE
    format: json
    requirements:
        _format: json|csv

# Icon
sulu_admin.get_icons:
    path: '/icons.{_format}'
    methods: GET
    controller: 'sulu_admin.icon_controller::cgetAction'
    format: json
    requirements:
        _format: json|csv

# Teaser
sulu_page.get_teasers:
    path: '/teasers.{_format}'
    methods: GET
    controller: 'sulu_admin.teaser_controller::cgetAction'
    format: json
    requirements:
        _format: json|csv

sulu_admin.get_items:
    path: '/items.{_format}'
    methods: GET
    controller: 'sulu_admin.smart_content_item_controller::getItemsAction'
    format: json
    requirements:
        _format: json|csv
