sulu_preview.get_preview-link:
    path: /preview-links/{resourceId}.{_format}
    methods: GET
    controller: sulu_preview.preview_link_controller::getAction
    format: json
    requirements:
        _format: json|csv

sulu_preview.post_preview_link_trigger:
    path: /preview-links/{resourceId}.{_format}
    controller: sulu_preview.preview_link_controller::postTriggerAction
    methods: POST
    format: json
    requirements:
        _format: json|csv
