sulu_activity.get_activities:
    path: /activities.{_format}
    controller: sulu_activity.activity_controller::cgetAction
    methods: GET
    format: json
    requirements:
        _format: json|csv
