sulu_tag.get_tag:
    path: /tags/{id}.{_format}
    controller: sulu_tag.tag_controller::getAction
    methods: GET
    format: json
    requirements:
       _format: json|csv

sulu_tag.get_tags:
    path: /tags.{_format}
    controller: sulu_tag.tag_controller::cgetAction
    methods: GET
    format: json
    requirements:
        _format: json|csv

sulu_tag.post_tag:
    path: /tags.{_format}
    controller: sulu_tag.tag_controller::postAction
    methods: POST
    format: json
    requirements:
        _format: json|csv

sulu_tag.put_tag:
    path: /tags/{id}.{_format}
    controller: sulu_tag.tag_controller::putAction
    methods: PUT
    format: json
    requirements:
        _format: json|csv

sulu_tag.delete_tag:
    path: /tags/{id}.{_format}
    controller: sulu_tag.tag_controller::deleteAction
    methods: DELETE
    format: json
    requirements:
        _format: json|csv

sulu_tag.patch_tags:
    path: /tags.{_format}
    controller: sulu_tag.tag_controller::cpatchAction
    methods: PATCH
    format: json
    requirements:
        _format: json|csv

sulu_tag.post_tag_merge:
    path: /tags/merge.{_format}
    controller: sulu_tag.tag_controller::postMergeAction
    methods: POST
    format: json
    requirements:
        _format: json|csv
