sulu_media.website.image.proxy:
    path: "%sulu_media.format_cache.media_proxy_path%"
    controller: sulu_media.media_stream_controller::getImageAction
    defaults:
        _requestAnalyzer: false
    requirements:
        slug: .*

sulu_media.website.media.download:
    path: "%sulu_media.media_manager.media_download_path%"
    controller: sulu_media.media_stream_controller::downloadAction
    defaults:
        _requestAnalyzer: false
    requirements:
        id: "\\d+"

sulu_media.website.media.download_admin:
    path: "%sulu_media.media_manager.media_download_path_admin%"
    controller: sulu_media.media_stream_controller::downloadAction
    defaults:
        _requestAnalyzer: false
    requirements:
        id: "\\d+"
