# CustomUrl
sulu_custom_url.cget_webspace_custom-urls:
    path: '/webspaces/{webspace}/custom-urls.{_format}'
    methods: GET
    controller: 'sulu_custom_urls.custom_url_controller::cgetAction'
    format: json
    requirements:
        _format: json|csv

sulu_custom_url.get_webspace_custom-urls:
    path: '/webspaces/{webspace}/custom-urls/{id}.{_format}'
    methods: GET
    controller: 'sulu_custom_urls.custom_url_controller::getAction'
    format: json
    requirements:
        _format: json|csv

sulu_custom_url.post_webspace_custom-urls:
    path: '/webspaces/{webspace}/custom-urls.{_format}'
    methods: POST
    controller: 'sulu_custom_urls.custom_url_controller::postAction'
    format: json
    requirements:
        _format: json|csv

sulu_custom_url.put_webspace_custom-urls:
    path: '/webspaces/{webspace}/custom-urls/{id}.{_format}'
    methods: PUT
    controller: 'sulu_custom_urls.custom_url_controller::putAction'
    format: json
    requirements:
        _format: json|csv

sulu_custom_url.delete_webspace_custom-urls:
    path: '/webspaces/{webspace}/custom-urls/{id}.{_format}'
    methods: DELETE
    controller: 'sulu_custom_urls.custom_url_controller::deleteAction'
    format: json
    requirements:
        _format: json|csv

sulu_custom_url.cdelete_webspace_custom-urls:
    path: '/webspaces/{webspace}/custom-urls.{_format}'
    methods: DELETE
    controller: 'sulu_custom_urls.custom_url_controller::cdeleteAction'
    format: json
    requirements:
        _format: json|csv

# CustomUrlRoute
sulu_custom_url.get_webspace_custom-urls_routes:
    path: '/webspaces/{webspace}/custom-urls/{id}/routes.{_format}'
    methods: GET
    controller: 'sulu_custom_urls.custom_url_route_controller::cgetAction'
    format: json
    requirements:
        _format: json|csv

sulu_custom_url.delete_webspace_custom-urls_routes:
    path: '/webspaces/{webspace}/custom-urls/{id}/routes.{_format}'
    methods: DELETE
    controller: 'sulu_custom_urls.custom_url_route_controller::cdeleteAction'
    format: json
    requirements:
        _format: json|csv
