name: Crowdin Upload

on:
    push:
        tags:
            - '*'
    workflow_dispatch:

jobs:
    upload_sources:
        name: Upload Sources
        runs-on: ubuntu-22.04
        timeout-minutes: 30

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: '2.6'

            - name: Prepare Directory
              run: |
                  mkdir -p var/translations

            - name: Merge all translation files from 2.6
              run: |
                  jq -s '.|add' src/Sulu/Bundle/*/Resources/translations/admin.en.json > var/translations/admin-merged-2-6.en.json

            - name: Output merged translations 2.6
              run: |
                  cat var/translations/admin-merged-2-6.en.json

            - name: Switch Branch to 3.0
              run: |
                  git fetch origin 3.0
                  git checkout origin/3.0

            - name: Merge all translation files from 3.0
              run: |
                  jq -s '.|add' src/Sulu/Bundle/*/Resources/translations/admin.en.json packages/*/translations/admin.en.json > var/translations/admin-merged-3-0.en.json

            - name: Output merged translations 3.0
              run: |
                  cat var/translations/admin-merged-3-0.en.json

            - name: Merge branches
              run: |
                  jq -s '.|add' var/translations/admin-merged-2-6.en.json var/translations/admin-merged-3-0.en.json > admin.en.json

            - name: Output merged all translations
              run: |
                  cat admin.en.json

            - name: Download Crowdin CLI
              run: curl "https://downloads.crowdin.com/cli/v3/crowdin-cli.zip" --output crowdin-cli.zip && unzip crowdin-cli.zip

            - name: Upload translations to crowdin
              env:
                  CROWDIN_TOKEN: ${{ secrets.CrowdinToken }}
              run: java -jar $(find . -name crowdin-cli.jar) upload sources -s "admin.en.json" -t "admin.%two_letters_code%.json" -i 15 --base-url=https://sulu.crowdin.com --base-path=. --token=$CROWDIN_TOKEN
